# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import smartchess_pb2 as smartchess__pb2


class SensorReadStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendSensorData = channel.unary_unary(
        '/SensorRead/sendSensorData',
        request_serializer=smartchess__pb2.SensorRequest.SerializeToString,
        response_deserializer=smartchess__pb2.SensorResponse.FromString,
        )


class SensorReadServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendSensorData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SensorReadServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendSensorData': grpc.unary_unary_rpc_method_handler(
          servicer.sendSensorData,
          request_deserializer=smartchess__pb2.SensorRequest.FromString,
          response_serializer=smartchess__pb2.SensorResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SensorRead', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
